Fix Signature repr()
libgit2/pygit2 pull request #1155
Opened 2022-08-14 23:50 UTC by JacobSwanson

`to_unicode()` expects a non-NULL `x` argument (due to `strlen(x)`);
however `self->encoding` _may_ be NULL, especially if built with
`build_signature()` (i.e. if called from the `commit.author` property).

As a result, any `repr()` on a `Signature` with a NULL `encoding` will
cause a segfault.

Other functions manually map NULL to "utf-8" (see
`Signature__encoding__get__()`), we we'll do the same thing here.

2022-08-17 09:07 UTC, jdavid commented
Good catch.

I think it would be more correct to represent `NULL` as `None`, so in this case the repr looks like:

```python
pygit2.Signature('Foo Ibáñez', 'foo@bar.com', 1322174594, 60, None)
```

Then for this to work `Signature_init` has to be changed to use `z` instead of `s`:

```C
    if (!PyArg_ParseTupleAndKeywords(
            args, kwds, "Os|Liz", keywords,
            &py_name, &email, &time, &offset, &encoding))
```

2022-08-18 21:44 UTC, JacobSwanson commented
Agreed that representation has better semantics.  Updated to reflect!

2022-08-21 14:43 UTC, jdavid requested changes
Also, please rebase, and squash into a single commit.

2022-08-21 14:43 UTC, jdavid commented on src/signature.c
> +        NULL);
This change is not needed, since `to_unicode` already handles the case when the given `encoding` is `NULL`.

2022-08-21 14:43 UTC, jdavid commented on src/signature.c
> +        NULL);
idem as above

2022-08-21 14:43 UTC, jdavid commented on test/test_signature.py
> +    assert None == signature._encoding
Comparison with `None` is better done with the `is` operator.

2022-08-21 17:21 UTC, JacobSwanson commented
Fixed up! Let me know if there is anything else I can do.  Thanks

2022-08-22 11:59 UTC, jdavid commented
One more thing, `pygit2/_pygit2.pyi` needs to be updated. I think only `_encoding` and `__init__` are concerned:

```python
class Signature:
    _encoding: str | None
    ...
    def __init__(self, name: str, email: str, time: int, offset: int, encoding: str | None) -> None: ...
```

2022-08-23 08:21 UTC, merged

2022-08-23 08:30 UTC, jdavid commented
Merged, thanks!

2022-08-24 08:43 UTC, jdavid commented
FYI, after a second thought I've done follow up commit. The main change is that ``Signature._encoding`` will return ``utf-8`` when internally it's ``NULL``. This is to keep backwards compatibility, so users don't need to worry about handling ``None``.